version: "3.3"
volumes:
  postgresql:
  redis:
services:
  postgres:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # redis:
  #   image: redis:6.2.3
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/var/lib/redis/data